services:
  - type: web
    name: karaoke-shen
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
    disk:
      name: karaoke-data
      mountPath: /data
      sizeGB: 1
